#!/usr/bin/env bash

# script to setup new image (best to do on each intellij version bump)
# TODO this could be generated by sbt to keep the IJ version in syncoc

NAME=ideprobe
read -p "Username: " USERNAME
IMAGE=${USERNAME}/${NAME}
IJ_VERSION=202.6397.20

rm -f Dockerfile || true && cp ci/image/Dockerfile Dockerfile || exit 1

docker login --username="$USERNAME"
DOCKER_BUILDKIT=1 BUILDKIT_PROGRESS=plain docker build --tag "$IMAGE:${IJ_VERSION}" .
docker push "${IMAGE}"