#!/bin/sh

export IDEPROBE_DISPLAY=xvfb
export JAVA_HOME=/usr/local/openjdk-11
export IDEPROBE_SCREENSHOTS_DIR=/tmp/ideprobe/screenshots

sbt "; clean ; junit-driver / test; driver-tests / test; api / test; probe-plugin / test; driver / test; benchmarks / test; probe-test-plugin / test"
