#!/bin/sh

export IDEPROBE_DISPLAY=xvfb
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk

sbt "; clean; ++2.13.1! ; probe-test-plugin / test; examples / test; junit-driver / test; driver / test; probe-plugin / test; api / test; ide-probe-wip / test; driver-tests / test"
