#!/bin/sh

export IDEPROBE_DISPLAY=xvfb
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk

sbt "; clean; ++2.13.1! ; scala-tests / test; scala-probe-plugin / test; scala-probe-driver / test; scala-probe-api / test"
