addSbtPlugin("org.jetbrains" % "sbt-idea-plugin" % "3.23.1")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.11.0")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.12")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.12.1")
addSbtPlugin("com.lucidchart" % "sbt-cross" % "4.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.2")
