#!/bin/sh

export IDEPROBE_DISPLAY=xvfb
export JAVA_HOME=/usr/local/openjdk-11
export IDEPROBE_SCREENSHOTS_DIR=/tmp/ideprobe/screenshots

sbt "; clean ; benchmarks_2_12 / test; probe-plugin_2_12 / test; driver_2_12 / test; probe-test-plugin_2_12 / test; api_2_12 / test; junit-driver_2_12 / test; driver-tests_2_12 / test"
