#!/bin/sh

export IDEPROBE_DISPLAY=xvfb
export JAVA_HOME=/usr/local/openjdk-11
export IDEPROBE_SCREENSHOTS_DIR=/tmp/ideprobe/screenshots

sbt "; clean ; pants-probe-api_2_12 / test; pants-probe-plugin_2_12 / test; pants-probe-driver_2_12 / test"
