#!/bin/sh

export IDEPROBE_DISPLAY=xvfb
export JAVA_HOME=/usr/local/openjdk-11

sbt "; clean; ++2.12.10! ; scala-tests / test; scala-probe-plugin / test; scala-probe-driver / test; scala-probe-api / test"
