#!/bin/sh

export IDEPROBE_DISPLAY=xvfb
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk

sbt clean && sbt "; probePlugin / test; junitDriver / test; driverTestPlugin / test; driver / test; api / test; driverTests / test"
